name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # chạy khi có code push lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t travellerapp .

      # 4. Tag Docker image
      - name: Tag Docker image
        run: |
          docker tag travellerapp ${{ secrets.DOCKER_USERNAME }}/travellerapp:latest

      # 5. Push Docker image lên Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/travellerapp:latest
